services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - MONGODB_DB_NAME=${DATABASE_NAME}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
