sonar.projectKey=adventure-booking-backend
sonar.organization=umer-atu
sonar.host.url=https://sonarcloud.io
sonar.projectName=Adventure Booking Backend
sonar.projectVersion=1.0

# Path to sources
sonar.sources=app
sonar.tests=tests

# Encoding
sonar.sourceEncoding=UTF-8

# Python specific
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11

# Exclusions
sonar.exclusions=**/__init__.py,app/core/config.py
